---
- name: Update cache repositories
  apt: update_cache=yes

- name: Upgrade all apt packages
  apt: upgrade=dist

- name: ensure npm is present
  apt: name=npm state=present update_cache=yes

- name: Add Nodesource Keys
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add Nodesource Apt Sources
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main'
    state: present

- name: Install NodeJS
  apt:
    name: nodejs
    state: latest
    update_cache: "yes"

- name: Install "pm2" node.js package 
  npm:
    name: pm2
    global: yes
